flask-movie/apps/controllers/cinemas/controllers.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, request

from apps.common.auth import signin_required
from apps.database.models import Cinema

app = Blueprint('cinemas', __name__, url_prefix='/cinemas')


@app.route('', methods=['GET'])
@signin_required
def index():
    return ''

flask-movie/apps/controllers/movies/__init__.py
# -*- coding: utf-8 -*-

flask-movie/apps/controllers/movies/controllers.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template

from apps.common.auth import signin_required
from apps.database.models import Movie

app = Blueprint('movies', __name__, url_prefix='/movies')


@app.route('', methods=['GET'])
@signin_required
def index():
    return ''

flask-movie/templates/movies/index.html
{% extends 'layout/base.html' %}

{% block head %}
  <title>movies</title>
{% endblock %}

{% block body %}
  <div class="container">
    {% include('layout/nav.html') %}
    <div class="card-group">
      {% for movie in movies %}
        <div class="card" style="">
          <img class="card-img-top" src="{{ movie.poster_url }}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">{{ movie.title }}</h5>
            <p class="card-text">{{ movie.description }}</p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">감독: {{ movie.director }}</li>
            <li class="list-group-item">상영 시간: {{ movie.running_time }}분</li>
            <li class="list-group-item">상영 등급: {{ movie.age_rating }}세 이용가</li>
          </ul>
          <div class="card-body">
            <a href="{{ url_for('cinemas.index', movie_id=movie.id) }}" class="card-link btn btn-primary">예매하기</a>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}